### ISSUE TITLE
April chat name elections

### ISSUE THREAD

**Issue by dev-two** [dev-two/awesome-chat-names#3]
So now we have these variants:

- ~~Чат для гендерных отщепенцев~~
- Анальный кариес
- Фрухлинг сешн
- Белпельмень
- Менеджеры анального звена
- Постапрелизм
- Когнитивный каскаданс
- Когнитивный попаданец
- Когнитивные покемоны

**Comment by dev-two** [comment]
I vote for "Постапрелизм" as it mirrors main idea of the chat and that we're "post" enough to display it in the name.

**Comment by GPinchukov** [comment]
Нью серверс оф данек находятся ин джормани а оур любимая лидия шваб лив ин джерман. Ви гона чууйз итс коз фрулинг итс джермания на немецком. Тхенкью фор атеншен

**Comment by dnlklbv** [comment]
I vote for "Постапрелизм" because we already live in May.

**Comment by dev-two** [comment]
With 66.6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666(6)% votes "**Постапрелизм**" wins.

Thanks to all the participants. 🎉
